# Generated by Django 2.2.3 on 2019-08-02 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0003_auto_20190802_0958'),
    ]

    operations = [
        migrations.AddField(
            model_name='referral',
            name='clicks',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
