# Generated by Django 2.2.3 on 2019-08-02 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0004_referral_clicks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referral',
            name='clicks',
        ),
    ]
